# 1. Builder Stage: JAR 파일 생성
FROM gradle:8.5-jdk21-jammy AS builder

WORKDIR /build

COPY gradlew ./
COPY gradle/ ./gradle/
COPY build.gradle settings.gradle ./

# 권한 있어야 gradlelew 실행가능
RUN chmod +x gradlew

# 라이브러리 캐시 활성화
RUN --mount=type=cache,target=/root/.gradle \
    ./gradlew dependencies --no-daemon

COPY . .

# 빌드 캐시 활성화
RUN --mount=type=cache,target=/root/.gradle \
    ./gradlew build --no-daemon -x test --build-cache

# --------------------------------------------------------
# 2. Extractor : JAR 파일 계층 분리
# 레이어 추출
RUN java -Djarmode=layertools -jar build/libs/*.jar extract --destination extracted


# --------------------------------------------------------
# 3. Runtime Stage: 최종 실행 이미지
FROM gcr.io/distroless/java21-debian12

WORKDIR /app

COPY --from=builder /build/extracted/dependencies/ ./
COPY --from=builder /build/extracted/spring-boot-loader/ ./
COPY --from=builder /build/extracted/snapshot-dependencies/ ./
COPY --from=builder /build/extracted/application/ ./

USER nonroot
EXPOSE 8080

ENV TZ=Asia/Seoul
ENV JAVA_TOOL_OPTIONS="-Duser.timezone=Asia/Seoul"

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]